services:
  main:
    build: .
    image: main-image
    container_name: api-container
    networks:
    - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dolmachi
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge