services:
  main:
    build: .
    image: main-image
    container_name: main-container
    networks:
    - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dolmachi
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - ./data/mongo-dump:/dump:ro
      - ./scripts/restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
